/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    events: Event;
    'gallery-images': GalleryImage;
    'gallery-categories': GalleryCategory;
    'menu-items': MenuItem;
    'menu-categories': MenuCategory;
    notifications: Notification;
    'mailing-list': MailingList;
    reservations: Reservation;
    'contact-messages': ContactMessage;
    'opening-exceptions': OpeningException;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'mailing-list': MailingListSelect<false> | MailingListSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'opening-exceptions': OpeningExceptionsSelect<false> | OpeningExceptionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'nl' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Beheer wie toegang heeft tot dit admin paneel. Admins kunnen alles doen, editors kunnen alleen inhoud beheren.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins hebben volledige toegang, editors kunnen alleen inhoud bewerken
   */
  role: 'admin' | 'editor';
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Upload afbeeldingen die je kunt gebruiken in blogposts, de galerij, menukaart en andere plekken op de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijf de afbeelding kort voor slechtzienden en zoekmachines, bijv. 'Gerecht met seizoensgroenten op een houten bord'
   */
  alt: string;
  /**
   * Optioneel bijschrift dat onder de afbeelding kan verschijnen
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Schrijf blogposts over recepten, evenementen, verhalen en nieuws. Gepubliceerde posts verschijnen op de Blog-pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Het deel van de URL na /blog/, bijv. 'welkom-bij-de-bees-hive'
   */
  slug: string;
  /**
   * Korte samenvatting die verschijnt op de blogpagina en in zoekmachines (max 300 tekens)
   */
  excerpt: string;
  /**
   * Mag leeg blijven. Een blogpost zonder foto kan prima en krijgt vanzelf een getekende plaat, dus wacht niet met publiceren tot er een goede foto is.
   */
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Categorie helpt bezoekers bij het filteren
   */
  category?: ('news' | 'recipes' | 'events' | 'stories' | 'tips') | null;
  /**
   * Voeg tags toe voor betere vindbaarheid, bijv. 'Zuid-Afrika', 'seizoensgebonden', 'workshop'
   */
  tags?: string[] | null;
  /**
   * Alleen gepubliceerde posts zijn zichtbaar op de website
   */
  status: 'draft' | 'published';
  /**
   * Datum die getoond wordt bij de post
   */
  publishedDate?: string | null;
  author?: (number | null) | User;
  meta?: {
    /**
     * De blauwe regel in de zoekresultaten. Rond de 60 tekens; langer wordt afgekapt. Laat leeg om de titel van de pagina zelf te gebruiken.
     */
    title?: string | null;
    /**
     * De twee regels onder de titel, in Google en in een gedeelde link. Rond de 160 tekens.
     */
    description?: string | null;
    /**
     * De foto die verschijnt als iemand deze pagina deelt op WhatsApp, Facebook of LinkedIn. Eén foto voor beide talen. Je hoeft hem niet apart in het Engels te kiezen. Liefst liggend; hij wordt automatisch bijgesneden naar 1200 bij 630 pixels.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Alles wat er bij jullie te doen is: eenmalige avonden en terugkerende afspraken. Vul bij een terugkerend evenement één keer de eerste datum in en kies daaronder hoe vaak het terugkomt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Twee of drie zinnen die in de agenda onder de titel komen te staan (max 300 tekens)
   */
  excerpt: string;
  /**
   * Het hele verhaal, zoals het op de pagina van dit evenement komt te staan
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mag leeg blijven. Een evenement zonder foto krijgt vanzelf een getekende plaat.
   */
  image?: (number | null) | Media;
  /**
   * Datum én tijd. Bij een terugkerend evenement is dit de eerste keer, en het tijdstip geldt voor alle volgende keren.
   */
  startDate: string;
  /**
   * Laat leeg als het einde niet vaststaat.
   */
  endDate?: string | null;
  /**
   * Vink aan als er geen begintijd te noemen is.
   */
  allDay?: boolean | null;
  /**
   * Komt dit vaker terug? Vul het hier in, dan verschijnt het vanzelf op alle volgende dagen.
   */
  recurrence?: {
    type?: ('none' | 'weekly' | 'biweekly' | 'monthlyWeekday' | 'monthlyDate') | null;
    weekday?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
    /**
     * Bijvoorbeeld: de laatste zondag van de maand.
     */
    ordinal?: ('first' | 'second' | 'third' | 'fourth' | 'last') | null;
    /**
     * Tot wanneer dit doorloopt. Laat leeg voor: voorlopig altijd.
     */
    until?: string | null;
    /**
     * Dagen waarop het een keer NIET doorgaat.
     */
    skipDates?:
      | {
          date: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Laat leeg voor bij ons in de zaak.
   */
  location?: string | null;
  /**
   * Bijv. '7,50' of 'Gratis'. Laat leeg als het niet van toepassing is.
   */
  price?: string | null;
  /**
   * Vink aan als mensen zich vooraf moeten opgeven.
   */
  bookingRequired?: boolean | null;
  /**
   * Volledige link naar het formulier of de ticketpagina. Laat leeg als mensen gewoon even bellen.
   */
  bookingUrl?: string | null;
  /**
   * Eén zin, bijvoorbeeld 'Vol is vol' of 'Bel even, dan zetten we je op de lijst'.
   */
  bookingNote?: string | null;
  /**
   * Categorie helpt bezoekers bij het filteren
   */
  category?: ('buurt' | 'muziek' | 'workshop' | 'proeverij' | 'feest' | 'overig') | null;
  /**
   * Het deel van de URL na /evenementen/
   */
  slug: string;
  /**
   * Alleen gepubliceerde evenementen staan op de site.
   */
  status: 'draft' | 'published';
  /**
   * Zet dit evenement bovenaan de agenda en op de voorpagina.
   */
  featured?: boolean | null;
  meta?: {
    /**
     * De blauwe regel in de zoekresultaten. Rond de 60 tekens; langer wordt afgekapt. Laat leeg om de titel van de pagina zelf te gebruiken.
     */
    title?: string | null;
    /**
     * De twee regels onder de titel, in Google en in een gedeelde link. Rond de 160 tekens.
     */
    description?: string | null;
    /**
     * De foto die verschijnt als iemand deze pagina deelt op WhatsApp, Facebook of LinkedIn. Eén foto voor beide talen. Je hoeft hem niet apart in het Engels te kiezen. Liefst liggend; hij wordt automatisch bijgesneden naar 1200 bij 630 pixels.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload foto's van het restaurant, gerechten, evenementen en meer. Ze verschijnen op de Galerij-pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  /**
   * Beschrijvende titel voor de foto
   */
  title: string;
  image: number | Media;
  /**
   * Bezoekers filteren hierop. Staat de categorie er nog niet bij, maak hem dan aan onder Galerij Categorieën.
   */
  category: number | GalleryCategory;
  /**
   * Uitgelichte foto's verschijnen als eerste
   */
  featured?: boolean | null;
  /**
   * Optioneel bijschrift dat in de lightbox verschijnt
   */
  description?: string | null;
  /**
   * Lagere nummers verschijnen eerst
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maak zelf categorieën aan om de galerij mee te filteren, bijv. Restaurant, Eten & Drinken, Sfeer, Kunst.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: number;
  /**
   * De knop waarop bezoekers filteren, bijv. 'Eten & Drinken'. Vertaal hem op het Engelse tabblad; blijft die leeg, dan wordt de Nederlandse naam getoond.
   */
  name: string;
  /**
   * Lagere nummers staan vooraan in de filterbalk
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Beheer alle gerechten en dranken. Stel prijzen in, voeg dieetwensen toe en markeer seizoensspecials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  /**
   * Korte beschrijving van het gerecht, bijv. ingrediënten of bereidingswijze
   */
  description?: string | null;
  /**
   * Prijs in euro's
   */
  price: number;
  category: number | MenuCategory;
  spicyLevel?: ('none' | 'mild' | 'medium' | 'hot') | null;
  /**
   * Optionele foto van het gerecht
   */
  image?: (number | null) | Media;
  /**
   * Selecteer alle relevante dieetwensen
   */
  dietary?: ('vegetarian' | 'vegan' | 'gluten-free' | 'dairy-free' | 'nut-free' | 'contains-fish')[] | null;
  /**
   * Vrij tekstveld voor allergenen, bijv. 'Bevat noten, gluten, ei'
   */
  allergens?: string | null;
  /**
   * Toon als aanbeveling op de kaart
   */
  featured?: boolean | null;
  /**
   * Markeer als seizoensgebonden
   */
  seasonal?: boolean | null;
  /**
   * Toon een 'Nieuw' badge
   */
  newItem?: boolean | null;
  /**
   * Zet uit als het gerecht tijdelijk niet beschikbaar is
   */
  available?: boolean | null;
  /**
   * Lagere nummers verschijnen eerst binnen de categorie
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maak categorieën aan voor de menukaart, bijv. Voorgerechten, Hoofdgerechten, Desserts, Dranken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  /**
   * Bijv. 'Voorgerechten', 'Hoofdgerechten', 'Desserts'
   */
  name: string;
  /**
   * Optionele korte tekst onder de categorienaam op de kaart, bijv. 'Om te beginnen'
   */
  description?: string | null;
  /**
   * Optioneel emoji-icoon, bijv. 🍽️ of 🥂
   */
  icon?: string | null;
  /**
   * Lagere nummers verschijnen eerst op de kaart
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Meldingen verschijnen als banner bovenaan de website. Gebruik ze voor aanbiedingen, evenementen of belangrijke berichten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Korte, opvallende titel voor de melding
   */
  title: string;
  /**
   * Het volledige bericht dat bezoekers zien
   */
  message: string;
  /**
   * Bepaalt de kleur van de banner
   */
  type: 'info' | 'offer' | 'event' | 'important';
  /**
   * Kunnen bezoekers de melding sluiten?
   */
  dismissible?: boolean | null;
  /**
   * Toon als banner bovenaan of als pop-up venster
   */
  displayMode?: ('banner' | 'popup') | null;
  /**
   * URL naar meer informatie, bijv. een blogpost of externe pagina
   */
  link?: string | null;
  /**
   * Vanaf wanneer is de melding zichtbaar?
   */
  startDate?: string | null;
  /**
   * Tot en met welke dag is de melding zichtbaar? De hele dag telt mee.
   */
  endDate?: string | null;
  /**
   * Zet uit om de melding tijdelijk te verbergen
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle e-mailadressen van bezoekers die zich hebben aangemeld voor de nieuwsbrief. Exporteer deze lijst om nieuwsbrieven te versturen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailing-list".
 */
export interface MailingList {
  id: number;
  email: string;
  name?: string | null;
  subscribedAt?: string | null;
  /**
   * Zet uit om iemand uit te schrijven zonder te verwijderen
   */
  active?: boolean | null;
  /**
   * Interne notities over deze abonnee
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aanvragen die via het reserveringsformulier binnenkomen. Een aanvraag is nog geen bevestiging: bel of mail de gast en zet daarna de status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  name: string;
  email: string;
  /**
   * Hierop bevestigen we de tafel
   */
  phone: string;
  guests: number;
  date: string;
  time: string;
  /**
   * Hoe lang deze tafel bezet is. Leeg = de standaard uit Site Instellingen.
   */
  duration?: number | null;
  /**
   * Allergieën, verjaardag, kinderstoel, een rustige tafel: wat de gast doorgeeft.
   */
  notes?: string | null;
  /**
   * Komt op de gedeelde gastenpagina te staan, dus iedereen die de link krijgt leest dit mee. Schrijf het aan het gezelschap zelf, bijvoorbeeld: "we houden de grote tafel bij het raam voor jullie vrij". Laat leeg als er niets te melden is.
   */
  guestNote?: string | null;
  /**
   * Het formulier vraagt hier niet meer naar; de gasten vonden het een vreemde vraag. Wat een gast nu doorgeeft staat bij Opmerkingen. Oude aanvragen houden hun antwoord.
   */
  occasion?: string | null;
  /**
   * Wat het gezelschap zelf heeft doorgegeven via de gedeelde link.
   */
  guestResponses?:
    | {
        name?: string | null;
        addedAt?: string | null;
        /**
         * Wat deze persoon niet eet, gescheiden door komma's
         */
        dietary?: string | null;
        drinks?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Nieuw is nog niet bevestigd. Zet op bevestigd zodra de gast bericht heeft.
   */
  status?: ('nieuw' | 'gebeld' | 'bevestigd' | 'geannuleerd') | null;
  /**
   * Of het bijbehorende mailtje de deur uit is. Een mislukt bericht kan opnieuw verstuurd worden door de status terug op "In de wachtrij" te zetten en op te slaan.
   */
  emailStatus?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
  /**
   * Wat de mailserver terugmeldde. Handig om door te sturen als het blijft misgaan.
   */
  emailError?: string | null;
  emailSentAt?: string | null;
  /**
   * Het geheime deel van de deelbare link naar de gastenpagina. Iedereen met die link kan de reservering zien en aanvullen, dus deel hem alleen met het gezelschap. Wordt er een nieuwe sleutel gemaakt, dan werkt de oude link niet meer.
   */
  guestToken?: string | null;
  /**
   * Wordt automatisch ingevuld
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Berichten die via het contactformulier binnenkomen. Ieder bericht staat hier ook als het mailtje niet is aangekomen, dus dit is de plek om te kijken of iemand nog wacht op antwoord.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  /**
   * Wat de bezoeker zelf heeft geschreven
   */
  message: string;
  /**
   * Voor jullie zelf: wat je hebt afgesproken, of wie het oppakt. De bezoeker ziet dit niet.
   */
  notes?: string | null;
  /**
   * Zet op beantwoord zodra iemand teruggemaild heeft, en op gearchiveerd als het klaar is.
   */
  status?: ('nieuw' | 'beantwoord' | 'gearchiveerd') | null;
  /**
   * Of het bijbehorende mailtje de deur uit is. Een mislukt bericht kan opnieuw verstuurd worden door de status terug op "In de wachtrij" te zetten en op te slaan.
   */
  emailStatus?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
  /**
   * Wat de mailserver terugmeldde. Handig om door te sturen als het blijft misgaan.
   */
  emailError?: string | null;
  emailSentAt?: string | null;
  /**
   * Welke taalversie van de site iemand las toen hij het formulier invulde. Handig om te weten in welke taal je antwoordt.
   */
  locale?: string | null;
  /**
   * Wordt automatisch ingevuld
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hiermee zetten jullie een enkele dag dicht of juist open, los van het normale weekschema. Een terugkerende regel (bijvoorbeeld elke laatste zondag van de maand) staat bij Site Instellingen -> Contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-exceptions".
 */
export interface OpeningException {
  id: number;
  /**
   * De dag waar het om gaat. Eén rij per dag.
   */
  date: string;
  /**
   * Vink aan als jullie die dag dicht zijn.
   */
  closed?: boolean | null;
  /**
   * Bijvoorbeeld '11:00 - 21:00'. Alleen invullen als jullie die dag open zijn, maar op andere tijden dan normaal.
   */
  hours?: string | null;
  /**
   * Wat er die dag aan de hand is; dit komt op de site te staan, bijvoorbeeld 'Eerste Kerstdag' of 'Besloten feest'.
   */
  note?: string | null;
  /**
   * Uit zetten als de dag wel meetelt voor reserveringen, maar niet apart genoemd hoeft te worden.
   */
  showOnSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: number | GalleryCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'mailing-list';
        value: number | MailingList;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'opening-exceptions';
        value: number | OpeningException;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  tags?: T;
  status?: T;
  publishedDate?: T;
  author?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  description?: T;
  image?: T;
  startDate?: T;
  endDate?: T;
  allDay?: T;
  recurrence?:
    | T
    | {
        type?: T;
        weekday?: T;
        ordinal?: T;
        until?: T;
        skipDates?:
          | T
          | {
              date?: T;
              id?: T;
            };
      };
  location?: T;
  price?: T;
  bookingRequired?: T;
  bookingUrl?: T;
  bookingNote?: T;
  category?: T;
  slug?: T;
  status?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  featured?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  category?: T;
  spicyLevel?: T;
  image?: T;
  dietary?: T;
  allergens?: T;
  featured?: T;
  seasonal?: T;
  newItem?: T;
  available?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  type?: T;
  dismissible?: T;
  displayMode?: T;
  link?: T;
  startDate?: T;
  endDate?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailing-list_select".
 */
export interface MailingListSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  subscribedAt?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  guests?: T;
  date?: T;
  time?: T;
  duration?: T;
  notes?: T;
  guestNote?: T;
  occasion?: T;
  guestResponses?:
    | T
    | {
        name?: T;
        addedAt?: T;
        dietary?: T;
        drinks?: T;
        id?: T;
      };
  status?: T;
  emailStatus?: T;
  emailError?: T;
  emailSentAt?: T;
  guestToken?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  notes?: T;
  status?: T;
  emailStatus?: T;
  emailError?: T;
  emailSentAt?: T;
  locale?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-exceptions_select".
 */
export interface OpeningExceptionsSelect<T extends boolean = true> {
  date?: T;
  closed?: T;
  hours?: T;
  note?: T;
  showOnSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  description?: string | null;
  /**
   * Komma-gescheiden, bijvoorbeeld: eetcafé Utrecht, lunch Zuilen, borrel. Google negeert deze tag sinds 2009 en gebruikt hem niet voor de ranking. Dat werk doen de Beschrijving hierboven en de tekst op de pagina's wel.
   */
  keywords?: string | null;
  /**
   * Komma-gescheiden lijst van keukens voor zoekmachines
   */
  cuisines?: string | null;
  priceRange?: string | null;
  /**
   * Link naar reserveringssysteem (bijv. formitable, couverts). Laat leeg om knop te verbergen.
   */
  reservationUrl?: string | null;
  contactEmail?: string | null;
  phone?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    area?: string | null;
    postalCode?: string | null;
    country?: string | null;
    countryCode?: string | null;
  };
  openingHours?:
    | {
        day: string;
        /**
         * Bijv. '11:00 – 21:00' of 'Gesloten'
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Voor een regel die elke maand terugkomt, bijvoorbeeld 'elke laatste zondag van de maand zijn we open'. Vul in de hoeveelste van de maand het is en welke dag, en daarna óf jullie die dag juist gesloten zijn óf van hoe laat tot hoe laat je open bent. Zo'n regel gaat vóór het gewone weekschema hierboven, maar een losse datum onder Afwijkende dagen gaat er weer overheen.
   */
  recurringOpenings?:
    | {
        ordinal: 'first' | 'second' | 'third' | 'fourth' | 'last';
        weekday: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * Aanvinken als jullie die dag dicht zijn. De tijden hieronder worden dan niet gebruikt.
         */
        closed?: boolean | null;
        /**
         * Bijvoorbeeld '11:00 - 21:00'.
         */
        hours?: string | null;
        /**
         * Korte regel die op de site bij deze dag komt te staan, bijvoorbeeld 'Zondagse brunch'. Laat leeg als het niet nodig is.
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Alleen een vrije regel tekst onder de openingstijden, meer niet: de site rekent er niets mee. Gaat het om een dag waarop jullie echt anders open of dicht zijn, zet die dan onder Afwijkende dagen (voor één datum) of in de terugkerende regels hierboven (voor iets dat elke maand terugkomt). Laat leeg als er niets te melden is: dan toont de site hier ook niets.
   */
  openingHoursNote?: string | null;
  /**
   * Plak hier de Google Maps embed URL. Ga naar Google Maps → Delen → Insluiten → kopieer de src URL uit de iframe code (begint met https://www.google.com/maps/embed). Let op: kopieer alleen de URL zelf, niet de hele iframe-code, en zorg dat er geen &#39; of &amp; in staat.
   */
  googleMapsEmbedUrl?: string | null;
  /**
   * Link naar jullie Google-vermelding, waar gasten de beoordelingen lezen en er zelf een achterlaten. Ga naar Google Maps → jullie zaak → Delen → Link kopiëren. Laat leeg als je dit blok niet op de contactpagina wilt.
   */
  googleReviewUrl?: string | null;
  socialMedia?: {
    instagram?: string | null;
    facebook?: string | null;
    tripadvisor?: string | null;
  };
  /**
   * De grote titel op de homepage. Gebruik | om het accent-woord te scheiden, bijv. 'De Bee's|Hive'
   */
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  /**
   * De drie foto's die naast de titel op de homepage staan. Laat dit helemaal leeg om de standaardfoto's te tonen. Zet je er zelf foto's in, doe er dan het liefst drie, in dezelfde volgorde als je ze op de site wilt zien.
   */
  heroImages?:
    | {
        image: number | Media;
        /**
         * Korte regel bij de foto. Laat leeg voor geen bijschrift.
         */
        caption?: string | null;
        /**
         * 100 is de foto zoals hij is. Lager zoomt uit, hoger zoomt in.
         */
        zoom?: number | null;
        /**
         * Welk deel van de foto altijd zichtbaar moet blijven als hij wordt bijgesneden. Staat het onderwerp bijvoorbeeld boven in beeld, kies dan Boven.
         */
        focalPoint?: ('center' | 'top' | 'bottom' | 'left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  newsletterTitle?: string | null;
  newsletterText?: string | null;
  /**
   * Het kleine regeltje onder het inschrijfveld. Mensen vullen hun e-mailadres eerder in als hier staat wat je ermee doet.
   */
  newsletterPrivacyNote?: string | null;
  aboutIntro?: string | null;
  /**
   * Het volledige verhaal op de Over Ons pagina. Gebruik de editor voor opmaak.
   */
  aboutStory?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Eén foto op de Over Ons pagina, onder de quote. Bijvoorbeeld de familie, de keuken of de zaak. Laat leeg als je hier niets wilt tonen. Staat er ook een video-URL ingevuld, dan wint de video.
   */
  aboutImage?: (number | null) | Media;
  /**
   * Plak de embed-URL van de video, bijv. https://www.youtube.com/embed/XXXXXXXXXXX of https://player.vimeo.com/video/123456789. Op YouTube: Delen → Insluiten → kopieer de src uit de iframe-code. Een gewone youtube.com/watch?v=... link werkt niet. Video's zelf uploaden kan hier niet, die worden te groot.
   */
  aboutVideoUrl?: string | null;
  /**
   * Eén korte regel onder de foto of video. Laat leeg voor geen bijschrift.
   */
  aboutMediaCaption?: string | null;
  /**
   * Uitvinken haalt het reserveringsformulier van de site. Gasten zien dan alleen nog het telefoonnummer. Handig bij een verbouwing of vakantie.
   */
  reservationsEnabled?: boolean | null;
  /**
   * Hoe lang een tafel gemiddeld bezet is.
   */
  reservationDurationMinutes?: number | null;
  /**
   * Hoeveel gasten er tegelijk aan tafel kunnen. Zit een tijdslot vol, dan is dat tijdstip niet meer te kiezen.
   */
  reservationCapacity?: number | null;
  /**
   * Boven dit aantal kan een gast niet zelf online boeken, maar vragen we hem contact op te nemen. Grote groepen wil je liever even spreken.
   */
  reservationMaxPartySize?: number | null;
  /**
   * Hoe kort van tevoren iemand nog online mag boeken.
   */
  reservationLeadMinutes?: number | null;
  /**
   * Verder dan dit aantal dagen vooruit staat de agenda dicht. Zo krijg je geen reservering binnen voor een datum waarvan je nog niets weet.
   */
  reservationHorizonDays?: number | null;
  /**
   * Geeft elke reservering een eigen deelbare pagina die de gast naar zijn gezelschap kan sturen.
   */
  guestPassEnabled?: boolean | null;
  /**
   * Wat het gezelschap alvast kan kiezen. Laat leeg om niets te vragen.
   */
  guestPassDrinks?:
    | {
        /**
         * Zoals de gast het te zien krijgt, bijv. 'Wijn' of 'Bier'.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Wat het gezelschap alvast kan aangeven, bijvoorbeeld 'Vegetarisch' of 'Notenallergie'. Laat leeg om er niet naar te vragen.
   */
  guestPassDietary?:
    | {
        /**
         * Zoals de gast het te zien krijgt.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Verschijnt als iemand een link naar de site deelt. Liefst 1200 bij 630 pixels.
   */
  shareImage?: (number | null) | Media;
  /**
   * De dikgedrukte regel op het kaartje. Laat leeg om de naam van de zaak en de titel van de pagina te gebruiken.
   */
  shareTitle?: string | null;
  /**
   * Het zinnetje onder de titel. Houd het kort, want de meeste apps kappen het na een regel of twee af. Laat leeg om de Beschrijving (SEO) onder Algemeen te gebruiken.
   */
  shareDescription?: string | null;
  /**
   * Geen eigen afbeelding? Dan maken we er zelf een met het logo en de naam.
   */
  shareImageAuto?: boolean | null;
  /**
   * Zet het meetscript op de site. Staat dit uit, dan wordt er niets gemeten en blijven de grafieken leeg.
   */
  umamiEnabled?: boolean | null;
  /**
   * Laat dit staan zoals het staat, tenzij jullie Umami op een eigen server draaien. Dan geeft Umami zelf het juiste adres.
   */
  umamiScriptUrl?: string | null;
  /**
   * Het lange nummer met streepjes dat Umami bij jullie website toont (Settings → Websites). Zonder dit nummer meet Umami niets.
   */
  umamiWebsiteId?: string | null;
  /**
   * Waar Umami draait, bijvoorbeeld https://cloud.umami.is. Nodig om de cijfers in dit paneel te tonen.
   */
  umamiHostUrl?: string | null;
  /**
   * Let op: dit is een sleutel, behandel hem als een wachtwoord en deel hem met niemand. Hij kan ook buiten dit scherm om worden ingesteld als de omgevingsvariabele UMAMI_API_KEY; staat die ingevuld, dan wint die en wordt wat hier staat genegeerd.
   */
  umamiApiKey?: string | null;
  /**
   * Als jullie zelf ingelogd zijn, tellen die bezoeken niet mee. Anders lijkt de site drukker dan hij is.
   */
  umamiDoNotTrackAdmin?: boolean | null;
  footerTagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  description?: T;
  keywords?: T;
  cuisines?: T;
  priceRange?: T;
  reservationUrl?: T;
  contactEmail?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        area?: T;
        postalCode?: T;
        country?: T;
        countryCode?: T;
      };
  openingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  recurringOpenings?:
    | T
    | {
        ordinal?: T;
        weekday?: T;
        closed?: T;
        hours?: T;
        note?: T;
        id?: T;
      };
  openingHoursNote?: T;
  googleMapsEmbedUrl?: T;
  googleReviewUrl?: T;
  socialMedia?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        tripadvisor?: T;
      };
  heroTitle?: T;
  heroSubtitle?: T;
  heroImages?:
    | T
    | {
        image?: T;
        caption?: T;
        zoom?: T;
        focalPoint?: T;
        id?: T;
      };
  newsletterTitle?: T;
  newsletterText?: T;
  newsletterPrivacyNote?: T;
  aboutIntro?: T;
  aboutStory?: T;
  aboutImage?: T;
  aboutVideoUrl?: T;
  aboutMediaCaption?: T;
  reservationsEnabled?: T;
  reservationDurationMinutes?: T;
  reservationCapacity?: T;
  reservationMaxPartySize?: T;
  reservationLeadMinutes?: T;
  reservationHorizonDays?: T;
  guestPassEnabled?: T;
  guestPassDrinks?:
    | T
    | {
        label?: T;
        id?: T;
      };
  guestPassDietary?:
    | T
    | {
        label?: T;
        id?: T;
      };
  shareImage?: T;
  shareTitle?: T;
  shareDescription?: T;
  shareImageAuto?: T;
  umamiEnabled?: T;
  umamiScriptUrl?: T;
  umamiWebsiteId?: T;
  umamiHostUrl?: T;
  umamiApiKey?: T;
  umamiDoNotTrackAdmin?: T;
  footerTagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}