/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    'gallery-images': GalleryImage;
    'gallery-categories': GalleryCategory;
    'menu-items': MenuItem;
    'menu-categories': MenuCategory;
    notifications: Notification;
    'mailing-list': MailingList;
    reservations: Reservation;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'mailing-list': MailingListSelect<false> | MailingListSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'nl' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Beheer wie toegang heeft tot dit admin paneel. Admins kunnen alles doen, editors kunnen alleen inhoud beheren.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins hebben volledige toegang, editors kunnen alleen inhoud bewerken
   */
  role: 'admin' | 'editor';
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Upload afbeeldingen die je kunt gebruiken in blogposts, de galerij, menukaart en andere plekken op de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijf de afbeelding kort voor slechtzienden en zoekmachines, bijv. 'Gerecht met seizoensgroenten op een houten bord'
   */
  alt: string;
  /**
   * Optioneel bijschrift dat onder de afbeelding kan verschijnen
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Schrijf blogposts over recepten, evenementen, verhalen en nieuws. Gepubliceerde posts verschijnen op de Blog-pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Het deel van de URL na /blog/, bijv. 'welkom-bij-de-bees-hive'
   */
  slug: string;
  /**
   * Korte samenvatting die verschijnt op de blogpagina en in zoekmachines (max 300 tekens)
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Categorie helpt bezoekers bij het filteren
   */
  category?: ('news' | 'recipes' | 'events' | 'stories' | 'tips') | null;
  /**
   * Voeg tags toe voor betere vindbaarheid, bijv. 'Zuid-Afrika', 'seizoensgebonden', 'workshop'
   */
  tags?: string[] | null;
  /**
   * Alleen gepubliceerde posts zijn zichtbaar op de website
   */
  status: 'draft' | 'published';
  /**
   * Datum die getoond wordt bij de post
   */
  publishedDate?: string | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload foto's van het restaurant, gerechten, evenementen en meer. Ze verschijnen op de Galerij-pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  /**
   * Beschrijvende titel voor de foto
   */
  title: string;
  image: number | Media;
  /**
   * Bezoekers filteren hierop. Staat de categorie er nog niet bij, maak hem dan aan onder Galerij Categorieën.
   */
  category: number | GalleryCategory;
  /**
   * Uitgelichte foto's verschijnen als eerste
   */
  featured?: boolean | null;
  /**
   * Optioneel bijschrift dat in de lightbox verschijnt
   */
  description?: string | null;
  /**
   * Lagere nummers verschijnen eerst
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maak zelf categorieën aan om de galerij mee te filteren, bijv. Restaurant, Eten & Drinken, Sfeer, Kunst.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: number;
  /**
   * De knop waarop bezoekers filteren, bijv. 'Eten & Drinken'. Vertaal hem op het Engelse tabblad; blijft die leeg, dan wordt de Nederlandse naam getoond.
   */
  name: string;
  /**
   * Lagere nummers staan vooraan in de filterbalk
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Beheer alle gerechten en dranken. Stel prijzen in, voeg dieetwensen toe en markeer seizoensspecials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  /**
   * Korte beschrijving van het gerecht, bijv. ingrediënten of bereidingswijze
   */
  description?: string | null;
  /**
   * Prijs in euro's
   */
  price: number;
  category: number | MenuCategory;
  spicyLevel?: ('none' | 'mild' | 'medium' | 'hot') | null;
  /**
   * Optionele foto van het gerecht
   */
  image?: (number | null) | Media;
  /**
   * Selecteer alle relevante dieetwensen
   */
  dietary?: ('vegetarian' | 'vegan' | 'gluten-free' | 'dairy-free' | 'nut-free' | 'contains-fish')[] | null;
  /**
   * Vrij tekstveld voor allergenen, bijv. 'Bevat noten, gluten, ei'
   */
  allergens?: string | null;
  /**
   * Toon als aanbeveling op de kaart
   */
  featured?: boolean | null;
  /**
   * Markeer als seizoensgebonden
   */
  seasonal?: boolean | null;
  /**
   * Toon een 'Nieuw' badge
   */
  newItem?: boolean | null;
  /**
   * Zet uit als het gerecht tijdelijk niet beschikbaar is
   */
  available?: boolean | null;
  /**
   * Lagere nummers verschijnen eerst binnen de categorie
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maak categorieën aan voor de menukaart, bijv. Voorgerechten, Hoofdgerechten, Desserts, Dranken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  /**
   * Bijv. 'Voorgerechten', 'Hoofdgerechten', 'Desserts'
   */
  name: string;
  /**
   * Optionele korte tekst onder de categorienaam op de kaart, bijv. 'Om te beginnen'
   */
  description?: string | null;
  /**
   * Optioneel emoji-icoon, bijv. 🍽️ of 🥂
   */
  icon?: string | null;
  /**
   * Lagere nummers verschijnen eerst op de kaart
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Meldingen verschijnen als banner bovenaan de website. Gebruik ze voor aanbiedingen, evenementen of belangrijke berichten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Korte, opvallende titel voor de melding
   */
  title: string;
  /**
   * Het volledige bericht dat bezoekers zien
   */
  message: string;
  /**
   * Bepaalt de kleur van de banner
   */
  type: 'info' | 'offer' | 'event' | 'important';
  /**
   * Kunnen bezoekers de melding sluiten?
   */
  dismissible?: boolean | null;
  /**
   * Toon als banner bovenaan of als pop-up venster
   */
  displayMode?: ('banner' | 'popup') | null;
  /**
   * URL naar meer informatie, bijv. een blogpost of externe pagina
   */
  link?: string | null;
  /**
   * Vanaf wanneer is de melding zichtbaar?
   */
  startDate?: string | null;
  /**
   * Tot en met welke dag is de melding zichtbaar? De hele dag telt mee.
   */
  endDate?: string | null;
  /**
   * Zet uit om de melding tijdelijk te verbergen
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle e-mailadressen van bezoekers die zich hebben aangemeld voor de nieuwsbrief. Exporteer deze lijst om nieuwsbrieven te versturen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailing-list".
 */
export interface MailingList {
  id: number;
  email: string;
  name?: string | null;
  subscribedAt?: string | null;
  /**
   * Zet uit om iemand uit te schrijven zonder te verwijderen
   */
  active?: boolean | null;
  /**
   * Interne notities over deze abonnee
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aanvragen die via het reserveringsformulier binnenkomen. Een aanvraag is nog geen bevestiging: bel of mail de gast en zet daarna de status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  name: string;
  /**
   * Optioneel; we bellen liever even
   */
  email?: string | null;
  /**
   * Hierop bevestigen we de tafel
   */
  phone: string;
  guests: number;
  date: string;
  time: string;
  /**
   * Bijvoorbeeld verjaardag, zakenlunch of familiediner
   */
  occasion?: string | null;
  /**
   * Wensen van de gast, allergieën, kinderstoel en dergelijke
   */
  notes?: string | null;
  /**
   * Nieuw is nog niet bevestigd. Zet op bevestigd zodra de gast bericht heeft.
   */
  status?: ('nieuw' | 'gebeld' | 'bevestigd' | 'geannuleerd') | null;
  /**
   * Wordt automatisch ingevuld
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: number | GalleryCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'mailing-list';
        value: number | MailingList;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  tags?: T;
  status?: T;
  publishedDate?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  featured?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  category?: T;
  spicyLevel?: T;
  image?: T;
  dietary?: T;
  allergens?: T;
  featured?: T;
  seasonal?: T;
  newItem?: T;
  available?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  type?: T;
  dismissible?: T;
  displayMode?: T;
  link?: T;
  startDate?: T;
  endDate?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailing-list_select".
 */
export interface MailingListSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  subscribedAt?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  guests?: T;
  date?: T;
  time?: T;
  occasion?: T;
  notes?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  description?: string | null;
  /**
   * Komma-gescheiden lijst van keukens voor zoekmachines
   */
  cuisines?: string | null;
  priceRange?: string | null;
  /**
   * Link naar reserveringssysteem (bijv. formitable, couverts). Laat leeg om knop te verbergen.
   */
  reservationUrl?: string | null;
  contactEmail?: string | null;
  phone?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    area?: string | null;
    postalCode?: string | null;
    country?: string | null;
    countryCode?: string | null;
  };
  openingHours?:
    | {
        day: string;
        /**
         * Bijv. '11:00 – 21:00' of 'Gesloten'
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vrij veld voor alles wat niet in het weekschema past. Bijvoorbeeld: 'Elke laatste zondag van de maand zijn we open' of een aangepaste tijd rond de feestdagen. Laat leeg als er niets bijzonders is: dan toont de site hier ook niets.
   */
  openingHoursNote?: string | null;
  /**
   * Plak hier de Google Maps embed URL. Ga naar Google Maps → Delen → Insluiten → kopieer de src URL uit de iframe code (begint met https://www.google.com/maps/embed). Let op: kopieer alleen de URL zelf, niet de hele iframe-code, en zorg dat er geen &#39; of &amp; in staat.
   */
  googleMapsEmbedUrl?: string | null;
  /**
   * Link naar jullie Google-vermelding, waar gasten de beoordelingen lezen en er zelf een achterlaten. Ga naar Google Maps → jullie zaak → Delen → Link kopiëren. Laat leeg als je dit blok niet op de contactpagina wilt.
   */
  googleReviewUrl?: string | null;
  socialMedia?: {
    instagram?: string | null;
    facebook?: string | null;
    tripadvisor?: string | null;
  };
  /**
   * De grote titel op de homepage. Gebruik | om het accent-woord te scheiden, bijv. 'De Bee's|Hive'
   */
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  newsletterTitle?: string | null;
  newsletterText?: string | null;
  aboutIntro?: string | null;
  /**
   * Het volledige verhaal op de Over Ons pagina. Gebruik de editor voor opmaak.
   */
  aboutStory?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Eén foto op de Over Ons pagina, onder de quote. Bijvoorbeeld de familie, de keuken of de zaak. Laat leeg als je hier niets wilt tonen. Staat er ook een video-URL ingevuld, dan wint de video.
   */
  aboutImage?: (number | null) | Media;
  /**
   * Plak de embed-URL van de video, bijv. https://www.youtube.com/embed/XXXXXXXXXXX of https://player.vimeo.com/video/123456789. Op YouTube: Delen → Insluiten → kopieer de src uit de iframe-code. Een gewone youtube.com/watch?v=... link werkt niet. Video's zelf uploaden kan hier niet, die worden te groot.
   */
  aboutVideoUrl?: string | null;
  /**
   * Eén korte regel onder de foto of video. Laat leeg voor geen bijschrift.
   */
  aboutMediaCaption?: string | null;
  footerTagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  description?: T;
  cuisines?: T;
  priceRange?: T;
  reservationUrl?: T;
  contactEmail?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        area?: T;
        postalCode?: T;
        country?: T;
        countryCode?: T;
      };
  openingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  openingHoursNote?: T;
  googleMapsEmbedUrl?: T;
  googleReviewUrl?: T;
  socialMedia?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        tripadvisor?: T;
      };
  heroTitle?: T;
  heroSubtitle?: T;
  newsletterTitle?: T;
  newsletterText?: T;
  aboutIntro?: T;
  aboutStory?: T;
  aboutImage?: T;
  aboutVideoUrl?: T;
  aboutMediaCaption?: T;
  footerTagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}